name: Update documentation every 12 hours
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Gradle cache
        uses: actions/cache@v3.0.5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-test-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-test-gradle-
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Generate documentation
        run: rm -rf docs && ./gradlew dokkaHtml && echo "haru.floofy.dev" >> docs/CNAME
        
      - name: Setup Git configuration
        run: |
          git config --global user.name 'Noel[bot]'
          git config --global user.email 'ohlookitsaugust@gmail.com'
          git config --global committer.email 'ohlookitsaugust@gmail.com'
          git config --global committer.name 'Noel[bot]'
          
      - name: Check if git status is dirty
        id: git_status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
              echo '::set-output name=STATUS_DIRTY::true'
          else
            echo '::set-output name=STATUS_DIRTY::false'
          fi
      - name: Commit changes (if dirty)
        if: contains(steps.git_status.outputs.STATUS_DIRTY, 'true')
        run: |
          git config --global user.name "Noel[bot]"
          git config --global user.email "ohlookitsaugust@gmail.com"
          
          git add .
          git commit -m "docs: up to date."
          git push -u origin master

