name: Build / Linting errors
on:
  pull_request:
  push:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - staging
      - master
    paths-ignore:
      - '.github/**'
      - 'assets/'
      - .dockerignore
      - gradle.properties
      - '**.md'
      - LICENSE
      - renovate.json
      - settings.gradle.kts
jobs:
  ktlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Since Haru can be ran from JDK <11, let's make sure that it works on JDK 11, 15, and 16!
        java-version: [11, 15, 16]

    steps:
      - name: Checks out the repository
        uses: actions/checkout@v3

      - name: Sets up Java v${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: adopt # AdoptOpenJDK is <3
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-test-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-test-gradle-

      - name: Lets ./gradlew be executable
        run: chmod +x ./gradlew

      - name: Lints the repository for any code errors
        run: ./gradlew spotlessCheck

      - name: Builds the project for any errors
        run: ./gradlew compileKotlin
